
### Requests from clinent App

### GET req
get http://localhost:3000/user-api/users

### get a user by id
get http://localhost:3000/user-api/users/2

### POST req
post http://localhost:3000/user-api/user
Content-Type: application/json

{
    "id":5,
    "name":"vika",
    "age":44
}

### PUT req
put http://localhost:3000/user-api/user
Content-Type: application/json

{
  "id":1,
  "name":"Kiran kumar",
  "age":25
}

### DELETE req
DELETE http://localhost:3000/user-api/users/2

